trigger:
  branches:
    include:
      - master  # Replace or add branches you want to monitor, e.g. main

pool: Default

stages:
  - stage: Restore
    jobs:
      - job: RestoreJob
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: 'sdk'
              version: '9.x'  # Use .NET 9.x or your target version
              installationPath: $(Agent.ToolsDirectory)/dotnet

          - checkout: self
            clean: true

          - script: dotnet restore BTM.IdentityServer/BTM.Duende.ASPIdentity/BTM.Duende.ASPIdentity.csproj
            displayName: 'Restore dependencies'
            workingDirectory: BTM.IdentityServer/BTM.Duende.ASPIdentity

  - stage: Build
    dependsOn: Restore
    jobs:
      - job: BuildJob
        steps:
          - script: dotnet build BTM.IdentityServer/BTM.Duende.ASPIdentity/BTM.Duende.ASPIdentity.csproj --configuration Release
            displayName: 'Build project'
            workingDirectory: BTM.IdentityServer/BTM.Duende.ASPIdentity

  - stage: Test
    dependsOn: Build
    jobs:
      - job: TestJob
        steps:
          - task: UseDotNet@2
            displayName: 'Install .NET SDK'
            inputs:
              packageType: 'sdk'
              version: '9.x'  # Keep consistent with restore/build

          # Add your test commands below, e.g.:
          # - script: dotnet test ...
